### ISSUE TITLE
More highlights

### ISSUE THREAD

**Issue by c0r73x** [bagrat/vim-buffet#18]
Would it be possible to add highlights for new and modified buffers aswell? Also a symbol and highlight for readonly would be nice.

**Comment by bagrat** [comment]
@c0r73x it is definitely possible to do what you have described. Not sure when I can work on that, but please feel free to submit a PR if you would like to hack on it yourself. If so, please let me know and I can provide some hints on where to start. Otherwise, stay tuned and I will post updates here.

**Comment by c0r73x** [comment]
I made a PR with modified buffers (https://github.com/bagrat/vim-buffet/pull/19). I will check the other types later, but now I have to do some work :P

**Comment by bagrat** [comment]
Awesome! Thanks @c0r73x, merged!
